# Generated by Django 3.2 on 2021-04-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SlugField(max_length=180)),
                ('alter_title', models.CharField(blank=True, max_length=180, null=True)),
                ('description', models.TextField(blank=True, max_length=666, null=True)),
                ('date_emission', models.DateTimeField(blank=True, null=True)),
                ('cover_path', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('LN', 'Light novel'), ('WN', 'Web novel')], default='LN', max_length=2)),
                ('structure', models.CharField(choices=[('VOL', 'Volumes'), ('CHA', 'Chapters')], default=0, max_length=3)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('n_likes', models.IntegerField()),
                ('n_dislikes', models.IntegerField()),
                ('n_views', models.IntegerField()),
            ],
        ),
    ]
