# Generated by Django 3.2 on 2021-05-07 07:21

import apps.novels.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Distro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('numero', models.SmallIntegerField(verbose_name='Volumen número')),
                ('description', models.TextField(blank=True, max_length=666, null=True)),
                ('cover_path', models.FilePathField(blank=True, null=True, path='media/novels', recursive=True)),
                ('emision_date', models.DateField(blank=True, null=True, verbose_name='Fecha de emisión')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('likes', models.IntegerField(default=0, editable=False)),
                ('dislikes', models.IntegerField(default=0, editable=False)),
                ('views', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Distribución',
                'verbose_name_plural': 'Distribuciones',
            },
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('alter_title', models.CharField(blank=True, max_length=180, null=True)),
                ('description', models.TextField(blank=True, max_length=666, null=True)),
                ('date_emission', models.DateField(blank=True, null=True)),
                ('cover_path', models.FilePathField(blank=True, null=True, path='media/novels', recursive=True)),
                ('type', models.CharField(choices=[('LN', 'Light novel'), ('WN', 'Web novel')], default='LN', max_length=2, verbose_name='Tipo')),
                ('structure', models.CharField(choices=[('VOL', 'Volumes'), ('ARC', 'Arcs'), ('CHA', 'Chapters')], default='VOL', max_length=3, verbose_name='Estructura')),
                ('genre', multiselectfield.db.fields.MultiSelectField(choices=[('---', ''), ('ATN', 'Action'), ('ADV', 'Adventure'), ('CLB', 'Celebrity'), ('CMD', 'Comedy'), ('DRM', 'Drama'), ('ECC', 'Ecchi'), ('FNT', 'Fantasy'), ('GNB', 'Gender Blender'), ('HRM', 'Harem'), ('HIS', 'Historical'), ('HOR', 'Horror'), ('JOS', 'Josei'), ('MLA', 'Martial Arts'), ('MTE', 'Mature'), ('MCA', 'Mecha'), ('MYS', 'Mystery'), ('PSY', 'Psychological'), ('ROM', 'Romance'), ('SCL', 'School Life'), ('SFI', 'Sci-fi'), ('SEI', 'Seinen'), ('STA', 'Shotacon'), ('SHO', 'Shoujo'), ('SAI', 'Shoujo Ai'), ('SOL', 'Slife of Life'), ('SOS', 'Sports'), ('SUP', 'Supernatural'), ('TRA', 'Tragedy'), ('WUX', 'Wuxia'), ('YAO', 'Yaoi'), ('YUI', 'Yuri')], default='---', max_length=127)),
                ('author', models.JSONField(null=True)),
                ('artist', models.JSONField(null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('likes', models.IntegerField(default=0, editable=False, verbose_name='Likes')),
                ('dislikes', models.IntegerField(default=0, editable=False, verbose_name='Dislikes')),
                ('views', models.IntegerField(default=0, editable=False, verbose_name='Vistas')),
            ],
            options={
                'verbose_name': 'Novela',
                'verbose_name_plural': 'Novelas',
            },
        ),
        migrations.CreateModel(
            name='Illustration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(blank=True, max_length=60, null=True)),
                ('picture', models.ImageField(upload_to=apps.novels.models.distro_directory_path)),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('distro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illustration_distro', to='novels.distro', verbose_name='Distribución')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illustration_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Ilustración',
                'verbose_name_plural': 'Ilustraciones',
            },
        ),
        migrations.AddField(
            model_name='distro',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distro_novel', to='novels.novel', verbose_name='Novela'),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=180, null=True)),
                ('numero', models.SmallIntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('new_content', models.BooleanField()),
                ('type', models.CharField(choices=[('PRO', 'Prologue'), ('EPI', 'Epilogue'), ('INT', 'Intermediate'), ('NOR', 'Normal'), ('ATW', 'Autor words'), ('SPE', 'Special')], default='NOR', max_length=3, null=True, verbose_name='Tipo')),
                ('distro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_distro', to='novels.distro', verbose_name='Distribución')),
            ],
            options={
                'verbose_name': 'Capítulo',
                'verbose_name_plural': 'Capítulos',
            },
        ),
    ]
