# Generated by Django 3.1.7 on 2021-04-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='n_dislikes',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='novel',
            name='n_likes',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='novel',
            name='n_views',
            field=models.IntegerField(editable=False),
        ),
    ]
