# Generated by Django 3.2 on 2021-05-07 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='new_content',
        ),
        migrations.AddField(
            model_name='chapter',
            name='last_content',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Último contenido'),
            preserve_default=False,
        ),
    ]
