# Generated by Django 3.2 on 2021-04-28 11:30

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_auto_20210418_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='genre',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('---', ''), ('ATN', 'Action'), ('ADV', 'Adventure'), ('CLB', 'Celebrity'), ('CMD', 'Comedy'), ('DRM', 'Drama'), ('ECC', 'Ecchi'), ('FNT', 'Fantasy'), ('GNB', 'Gender Blender'), ('HRM', 'Harem'), ('HIS', 'Historical'), ('HOR', 'Horror'), ('JOS', 'Josei'), ('MLA', 'Martial Arts'), ('MTE', 'Mature'), ('MCA', 'Mecha'), ('MYS', 'Mystery'), ('PSY', 'Psychological'), ('ROM', 'Romance'), ('SCL', 'School Life'), ('SFI', 'Sci-fi'), ('SEI', 'Seinen'), ('STA', 'Shotacon'), ('SHO', 'Shoujo'), ('SAI', 'Shoujo Ai'), ('SOL', 'Slife of Life'), ('SOS', 'Sports'), ('SUP', 'Supernatural'), ('TRA', 'Tragedy'), ('WUX', 'Wuxia'), ('YAO', 'Yaoi'), ('YUI', 'Yuri')], default='---', max_length=3),
        ),
    ]
