# Generated by Django 3.2 on 2021-05-07 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novels', '0002_auto_20210507_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_user', to='users.user', verbose_name='Actualizado por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distro',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='distro_user', to='users.user', verbose_name='Actualizado por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novel',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='novel_user', to='users.user', verbose_name='Actualizado por'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='novel',
            name='artist',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='novel',
            name='author',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
