# Generated by Django 3.1.7 on 2021-04-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_auto_20210408_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='structure',
            field=models.CharField(choices=[('VOL', 'Volumes'), ('CHA', 'Chapters')], default='VOL', max_length=3),
        ),
    ]
