# Generated by Django 3.2 on 2021-05-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0003_auto_20210507_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='last_content',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último contenido'),
        ),
    ]
