# Generated by Django 3.1.7 on 2021-04-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0003_auto_20210409_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='date_emission',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='novel',
            name='n_dislikes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='novel',
            name='n_likes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='novel',
            name='n_views',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='novel',
            name='title',
            field=models.CharField(max_length=180),
        ),
    ]
