# Generated by Django 3.2 on 2021-04-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0004_auto_20210430_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='views',
        ),
        migrations.AlterField(
            model_name='distro',
            name='cover_path',
            field=models.FilePathField(blank=True, null=True, path='media/novels', recursive=True),
        ),
        migrations.AlterField(
            model_name='novel',
            name='cover_path',
            field=models.FilePathField(blank=True, null=True, path='media/novels', recursive=True),
        ),
    ]
