# Generated by Django 3.2 on 2021-04-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0004_auto_20210430_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='cover_path',
            field=models.URLField(blank=True, null=True),
        ),
    ]
