# Generated by Django 3.2 on 2021-05-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0004_alter_chapter_last_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='views',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
