# Generated by Django 3.2 on 2021-04-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0004_auto_20210409_0042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novel',
            options={'verbose_name': 'Novela', 'verbose_name_plural': 'Novelas'},
        ),
        migrations.RenameField(
            model_name='novel',
            old_name='date_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='novel',
            old_name='date_updated',
            new_name='last_update',
        ),
        migrations.AlterField(
            model_name='novel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='n_dislikes',
            field=models.IntegerField(default=0, editable=False, verbose_name='Dislikes'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='n_likes',
            field=models.IntegerField(default=0, editable=False, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='n_views',
            field=models.IntegerField(default=0, editable=False, verbose_name='Views'),
        ),
    ]
