# Generated by Django 3.2 on 2021-04-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0005_alter_novel_cover_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='cover_path',
            field=models.FilePathField(blank=True, max_length=200, null=True, path='/media/novels', recursive=True),
        ),
    ]
