# Generated by Django 3.2 on 2021-04-09 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0005_auto_20210409_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novel',
            old_name='created',
            new_name='creation_date',
        ),
    ]
