# Generated by Django 3.2 on 2021-04-30 13:28

import apps.novels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0006_alter_novel_cover_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distro',
            name='cover_path',
            field=models.FilePathField(blank=True, null=True, path=apps.novels.models.image_path, recursive=True),
        ),
        migrations.AlterField(
            model_name='novel',
            name='cover_path',
            field=models.FilePathField(blank=True, null=True, path=apps.novels.models.image_path, recursive=True),
        ),
    ]
