# Generated by Django 3.2 on 2021-04-09 20:15

import apps.novels.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novels', '0006_rename_created_novel_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='cover_path',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='novel',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='n_views',
            field=models.IntegerField(default=0, editable=False, verbose_name='Vistas'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='structure',
            field=models.CharField(choices=[('VOL', 'Volumes'), ('CHA', 'Chapters')], default='VOL', max_length=3, verbose_name='Estructura'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='type',
            field=models.CharField(choices=[('LN', 'Light novel'), ('WN', 'Web novel')], default='LN', max_length=2, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, max_length=666, null=True)),
                ('cover_path', models.SlugField(blank=True, max_length=255, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('n_likes', models.IntegerField(default=0, editable=False, verbose_name='Likes')),
                ('n_dislikes', models.IntegerField(default=0, editable=False, verbose_name='Dislikes')),
                ('n_views', models.IntegerField(default=0, editable=False, verbose_name='Vistas')),
                ('novel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.novel')),
            ],
            options={
                'verbose_name': 'Volumen',
                'verbose_name_plural': 'Volúmenes',
            },
        ),
        migrations.CreateModel(
            name='Illustration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(blank=True, max_length=60, null=True)),
                ('picture', models.ImageField(upload_to=apps.novels.models.volume_directory_path)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('volume_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.volume')),
            ],
            options={
                'verbose_name': 'Ilustración',
                'verbose_name_plural': 'Ilustraciones',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=180, null=True)),
                ('number', models.SmallIntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('PRO', 'Prologue'), ('EPI', 'Epilogue'), ('INT', 'Intermediate'), ('NOR', 'Normal'), ('ATW', 'Autor words'), ('SPE', 'Special')], default='NOR', max_length=3, null=True, verbose_name='Tipo')),
                ('n_likes', models.IntegerField(default=0, editable=False, verbose_name='Likes')),
                ('n_dislikes', models.IntegerField(default=0, editable=False, verbose_name='Dislikes')),
                ('n_views', models.IntegerField(default=0, editable=False, verbose_name='Vistas')),
                ('volume_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.volume')),
            ],
            options={
                'verbose_name': 'Capítulo',
                'verbose_name_plural': 'Capítulos',
            },
        ),
    ]
