# Generated by Django 3.2 on 2021-04-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0007_auto_20210409_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='number',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='novel',
            name='structure',
            field=models.CharField(choices=[('VOL', 'Volumes'), ('ARC', 'Arcs'), ('CHA', 'Chapters')], default='VOL', max_length=3, verbose_name='Estructura'),
        ),
    ]
