# Generated by Django 3.2 on 2021-04-18 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fansub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('about', models.TextField(blank=True, max_length=666, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='fansubs/')),
                ('external_links', models.JSONField(null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('likes', models.IntegerField(default=0, editable=False)),
                ('dislikes', models.IntegerField(default=0, editable=False)),
                ('views', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Fansub',
                'verbose_name_plural': 'Fansubs',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank='False')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0, editable=False)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_fansub', to='novels.chapter')),
                ('fansub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_fansub', to='fansubs.fansub')),
            ],
            options={
                'verbose_name': 'Contribución',
                'verbose_name_plural': 'Contribuciones',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LE', 'Leader'), ('ME', 'Member'), ('TR', 'Traductor'), ('AR', 'Artist'), ('ED', 'Editor'), ('UP', 'Uploader')], default='ME', max_length=2, null=True, verbose_name='Rol')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de unión')),
                ('fansub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_fansub', to='fansubs.fansub')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
            },
        ),
        migrations.AddField(
            model_name='fansub',
            name='members',
            field=models.ManyToManyField(through='fansubs.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fansub',
            name='supports',
            field=models.ManyToManyField(through='fansubs.Support', to='novels.Chapter'),
        ),
    ]
