# Generated by Django 3.2 on 2021-05-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fansubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fansub',
            name='external',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
