# Generated by Django 3.2 on 2021-04-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fansubs', '0002_alter_fansub_external_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fansub',
            name='external_links',
        ),
        migrations.AddField(
            model_name='fansub',
            name='external',
            field=models.JSONField(default=[], null=True),
        ),
    ]
